export enum Routes {
  home = "/",
  login = "/login",
  signUp = "/sign-up",
  cart = "cart",
  wishlist = "wishlist",
  helpCenter = "help-center",
  contactUs = "contact-us",
  trackOrder = "track-order",
  aboutUs = "about-us",
  privacyPolicy = "privacy-policy",
  termsOfService = "terms-of-service",
  returnPolicy = "return-policy",
  faq = "faq",
  // search = "search",
}
